Arabic Translation
senky/phpbb-ext-akismet pull request #4
Opened 2019-06-14 07:40 UTC by alhitary

Plz accept the Arabic Language

2019-06-17 06:33 UTC, senky commented
@alhitary, could you, please, update your files with master branch? There are new keys that will be released in next version.

2019-06-18 06:06 UTC, senky requested changes

2019-06-18 06:06 UTC, senky commented on language/ar/akismet_acp.php
> +	'ACP_AKISMET_SKIP_CHECK_AFTER_N_POSTS_EXPLAIN'	=> 'القيمة صفر 0 تعني فحص جميع المشاركات. قد يكون ذلك مفيداً, لأنه في حالة تعرض حساب شخص ما للخطر, سيتم إرسال المشاركات المزعجة إلى قائمة الانتظار وبال
There are also new keys: `ACP_AKISMET_ADMIN_FORM_SETITNGS`, `ACP_AKISMET_CHECK_ADMIN_FORM` and `ACP_AKISMET_CHECK_ADMIN_FORM_EXPLAIN`.

2019-06-22 13:59 UTC, closed without merging

2019-06-22 14:01 UTC, alhitary commented
Dear Sir,

I did updated the files as your request :)

Thanks